### ISSUE TITLE
对 Obsidian 样式：段落首行增加缩进 进行一定补充：添加仅阅读模式下的首行缩进的css

### ISSUE THREAD

**Issue by PandaNocturne** [PKM-er/Pkmer-Docs#302]
## 对 [Obsidian 样式：段落首行增加缩进](https://pkmer.cn/Pkmer-Docs/10-obsidian/obsidian%E5%A4%96%E8%A7%82/css-%E7%89%87%E6%AE%B5/obsidian%E6%A0%B7%E5%BC%8F-%E6%AE%B5%E8%90%BD%E9%A6%96%E8%A1%8C%E5%A2%9E%E5%8A%A0%E7%BC%A9%E8%BF%9B/) 章节进行一定的补充：

对于该章节提供的2种 css 分别仅适用于 实时编辑和阅读模式 或者 实时和阅读两者：
> 前者并不能对阅读模式进行美化，后者在编辑模式时会对实际操作带来一些麻烦和不便

这里提供一种简单的 css ，仅适用于阅读模式下进行 **首行缩进** 的美化效果：
![image](https://github.com/PKM-er/Pkmer-Docs/assets/84729049/aabe8258-5d0e-4ddf-b1a5-952028f21489)

```css
p{
  /* border: solid 1px #ff0000; */
  /* font-family:"Times New Roman","宋体"; */
  text-decoration-line: none;
  margin: 10px 0px;
  line-height: 120%;
  text-indent: 2em;
  font-size: 20px;
}
```
